# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Organization'
  items:
    - label: 'Taking Notes'
      link: 'organization/taking-notes'
- label: 'Recon'
  items:
    - label: 'Passive'
      link: '/recon/passive'
    - label: 'Active'
      link: '/recon/active'
- label: 'Access'
  items:
    - label: 'Port List'
      link: '/access/port-list'
    - label: 'SSH'
      link: '/access/ssh'
- label: 'PrivEsc'
  items:
    - label: 'NIX'
      link: '/privesc/nix'
    - label: 'WIN'
      link: '/privesc/win'
- label: 'Infil / Exfil'
  items:
    - label: 'Netcat'
      link: '/infil-exfil/netcat'
- label: 'Cleanup'
  items:
    - label: 'Remove Artifacts'
      link: '/cleanup/remove-artifacts'
    - label: 'Timestomp'
      link: '/cleanup/timestomp'
- label: 'Additional Resources'
  link: '/additional-resources'
- label: 'Glossary'
  link: '/glossary'
